name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  run-and-test:
    runs-on: ubuntu-latest

    env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_REGION: ${{ secrets.S3_REGION }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Next.js Build
        run: npm run build

      - name: Run tests
        run: npm run test